### DistanceMetric

This class provides a uniform interface to fast distance metric functions. The various metrics can be accessed via the get_metric class method and the metric string identifier

**Available Metrics**

The following lists the string metric identifiers and the associated distance metric classes:

* Metrics intended for real-valued vector spaces:

|**Identifier**|**Class name in scikit-learn**|**Args**|**Distance function**|
|--------------|------------|------------|------------|
|`Euclidean`|EuclideanDistance|.|$sqrt(sum((x - y)^2))$|
|`Manhattan`|ManhattanDistance|.|$sum(x - y)$|
|`chebyshev`|ChebyshevDistance|.|$max(x - y)$|
|`minkowski`|MinkowskiDistance|p|$sum(x - y^p)^(1/p)$|
|`wminkowski`|WMinkowskiDistance|p, w|$sum(w * (x - y)^p)^(1/p)$|
|`seuclidean`|SEuclideanDistance|V|$sqrt(sum((x - y)^2 / V))$|
|`mahalanobis`|MahalanobisDistance|V or VI|$sqrt((x - y)' V^-1 (x - y))$|



**Metrics intended for two-dimensional vector spaces:**

* Note that the haversine distance metric requires data in the form of [latitude, longitude] and both inputs and outputs are in units of radians.

|**Identifier**|**Class name in scikit-learn**|**Distance function**|
|--------------|------------|------------|------------|
|`haversine`|HaversineDistance|$2 arcsin(sqrt(sin^2(0.5*dx) + cos(x1)cos(x2)sin^2(0.5*dy)))$|

In [2]:
from sklearn.neighbors import DistanceMetric
import numpy as np

euclidean_dist = DistanceMetric.get_metric('euclidean')
X = np.array([[0, 1, 2],[3, 4, 5]])
X

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
euclidean_dist.pairwise(X)

array([[0.        , 5.19615242],
       [5.19615242, 0.        ]])

In [4]:
Manhattan_dist = DistanceMetric.get_metric('manhattan')

In [5]:
Manhattan_dist.pairwise(X)

array([[0., 9.],
       [9., 0.]])

In [6]:
ChebyshevDistance = DistanceMetric.get_metric('chebyshev')

In [7]:
ChebyshevDistance.pairwise(X)

array([[0., 3.],
       [3., 0.]])

In [8]:
MinkowskiDistance = DistanceMetric.get_metric('minkowski')
MinkowskiDistance.pairwise(X)

array([[0.        , 5.19615242],
       [5.19615242, 0.        ]])

In [10]:
from scipy.spatial import distance
distance.wminkowski([1, 0, 0], [0, 1, 0], 1, np.ones(3))

2.0